// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SMEFLOWSystem.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;

namespace SMEFLOWSystem.Core.Entities;

public partial class Department : ITenantEntity
{
    /// <summary>Khóa chính</summary>
    public Guid Id { get; set; }

    /// <summary>Định danh Tenant (Multi-tenant isolation)</summary>
    public Guid TenantId { get; set; }

    /// <summary>Tên phòng ban</summary>
    public string Name { get; set; }

    /// <summary>Thời điểm tạo</summary>
    public DateTime? CreatedAt { get; set; }

    /// <summary>Thời điểm cập nhật gần nhất</summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>Cờ đánh dấu xóa mềm</summary>
    public bool? IsDeleted { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual ICollection<Position> Positions { get; set; } = new List<Position>();

    public virtual Tenant Tenant { get; set; }
    public virtual ICollection<Invite> Invites { get; set; } = new List<Invite>();

    /// <summary>Danh sách Manager được giao quyền quản lý phòng ban này</summary>
    public virtual ICollection<ManagerDepartment> ManagerDepartments { get; set; } = new List<ManagerDepartment>();
}