// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SMEFLOWSystem.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;

namespace SMEFLOWSystem.Core.Entities;

public partial class Employee : ITenantEntity
{
    /// <summary>Khóa chính của hồ sơ nhân viên</summary>
    public Guid Id { get; set; }

    /// <summary>Định danh Tenant (Multi-tenant isolation)</summary>
    public Guid TenantId { get; set; }

    /// <summary>FK → Users (Có thể null nếu nhân viên chưa được cấp tài khoản đăng nhập hệ thống)</summary>
    public Guid? UserId { get; set; }

    /// <summary>FK → Departments (Phòng ban trực thuộc)</summary>
    public Guid? DepartmentId { get; set; }

    /// <summary>FK → Positions (Chức vụ hiện tại của nhân viên)</summary>
    public Guid? PositionId { get; set; }

    /// <summary>Họ và tên đầy đủ</summary>
    public string FullName { get; set; }

    /// <summary>Số điện thoại liên hệ</summary>
    public string Phone { get; set; }

    /// <summary>Email liên lạc (công việc / cá nhân)</summary>
    public string Email { get; set; }

    /// <summary>Ngày bắt đầu gia nhập công ty</summary>
    public DateOnly HireDate { get; set; }

    /// <summary>Ngày nghỉ việc (nếu có)</summary>
    public DateOnly? ResignationDate { get; set; }

    /// <summary>Lương cơ bản dùng để tính toán trong hệ thống Payroll</summary>
    public decimal BaseSalary { get; set; }

    /// <summary>Trạng thái công việc (VD: Đang làm việc, Đã nghỉ việc, Thai sản...)</summary>
    public string Status { get; set; }

    /// <summary>Thời điểm tạo hồ sơ</summary>
    public DateTime? CreatedAt { get; set; }

    /// <summary>Thời điểm cập nhật hồ sơ gần nhất</summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>Cờ đánh dấu xóa mềm</summary>
    public bool? IsDeleted { get; set; }

    // ĐÃ XÓA BỎ QUAN HỆ ATTENDANCE CŨ - CHUẨN BỊ MAPPING VỚI RAWPUNCHLOG & DAILYTIMESHEET
    // public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual Department Department { get; set; }

    public virtual ICollection<Payroll> Payrolls { get; set; } = new List<Payroll>();

    public virtual Position Position { get; set; }

    public virtual Tenant Tenant { get; set; }

    public virtual User User { get; set; }
}