// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SMEFLOWSystem.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;

namespace SMEFLOWSystem.Core.Entities;

/// <summary>
/// Thông tin đơn đặt hàng gói SaaS.
/// </summary>
public partial class Order : ITenantEntity
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public string OrderNumber { get; set; }

    public Guid CustomerId { get; set; }

    public DateTime OrderDate { get; set; }

    /// <summary>Tổng tiền trước giảm giá.</summary>
    public decimal TotalAmount { get; set; }

    /// <summary>Số tiền giảm giá.</summary>
    public decimal? DiscountAmount { get; set; }

    /// <summary>Tổng tiền thanh toán cuối cùng.</summary>
    public decimal? FinalAmount { get; set; }

    /// <summary>Trạng thái thanh toán (Unpaid, Paid, v.v.).</summary>
    public string PaymentStatus { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Tenant Tenant { get; set; }
}