// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SMEFLOWSystem.SharedKernel.Interfaces;

namespace SMEFLOWSystem.Core.Entities;

/// <summary>
/// Chi tiết đơn hàng mua module gì.
/// </summary>
public partial class OrderItem : ITenantEntity
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public Guid OrderId { get; set; }

    /// <summary>Mô tả chi tiết hạng mục mua.</summary>
    public string Description { get; set; }

    /// <summary>Số lượng.</summary>
    public int Quantity { get; set; }

    /// <summary>Đơn giá.</summary>
    public decimal UnitPrice { get; set; }

    public decimal? TotalPrice { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}