// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SMEFLOWSystem.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;
using ShareKernel.Common.Enum;

namespace SMEFLOWSystem.Core.Entities;

/// <summary>
/// Bảng lương của từng nhân viên.
/// </summary>
public partial class Payroll : ITenantEntity
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public Guid EmployeeId { get; set; }

    /// <summary>Tháng tính lương.</summary>
    public int Month { get; set; }

    /// <summary>Năm tính lương.</summary>
    public int Year { get; set; }

    public int StandardWorkingDays { get; set; }      // Số ngày công chuẩn trong tháng
    public int ActualWorkingDays { get; set; }        // Số ngày đi làm thực tế
    public int TotalLateMinutes { get; set; }         // Tổng phút đi trễ
    public int TotalEarlyLeaveMinutes { get; set; }   // Tổng phút về sớm
    public int AbsentDays { get; set; }               // Số ngày vắng mặt
    public decimal TotalOTHours { get; set; }         // Tổng giờ OT

    public decimal BaseSalarySnapshot { get; set; }   // Lương cơ bản snapshot
    public decimal BasePay { get; set; }              // Lương sau khi tính prorated (BaseSalary * tỷ lệ ngày làm)
    public decimal OTPay { get; set; }                // Lương OT
    public decimal PenaltyFee { get; set; }           // Phạt đi trễ/về sớm

    public decimal StructuredBonus { get; set; }      // Tổng tiền thưởng tự động từ entries
    public decimal StructuredDeduction { get; set; }  // Tổng tiền khấu trừ tự động từ entries

    public decimal? CustomBonus { get; set; }         // Thưởng (Admin nhập tay)
    public decimal CustomDeduction { get; set; }      // Khấu trừ khác (Thuế/BHXH, Admin nhập tay)

    public decimal NetSalary { get; set; }            // Lương thực nhận cuối cùng

    /// <summary>Trạng thái bảng lương (Draft, Published).</summary>
    public PayrollStatus Status { get; set; } = PayrollStatus.Draft;

    public string? Notes { get; set; }                // Ghi chú (ví dụ: lý do phạt, thưởng)

    public DateTime? CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Tenant Tenant { get; set; }
}