// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SMEFLOWSystem.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;

namespace SMEFLOWSystem.Core.Entities;

public partial class Position : ITenantEntity
{
    /// <summary>Khóa chính</summary>
    public Guid Id { get; set; }

    /// <summary>Định danh Tenant (Multi-tenant isolation)</summary>
    public Guid TenantId { get; set; }

    /// <summary>FK → Department (Chức vụ này thuộc về phòng ban nào)</summary>
    public Guid DepartmentId { get; set; }

    /// <summary>Tên chức danh/chức vụ (VD: Trưởng phòng, Nhân viên...)</summary>
    public string Name { get; set; }

    /// <summary>Thời điểm tạo</summary>
    public DateTime? CreatedAt { get; set; }

    /// <summary>Thời điểm cập nhật gần nhất</summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>Cờ đánh dấu xóa mềm</summary>
    public bool? IsDeleted { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual Tenant Tenant { get; set; }
    public virtual ICollection<Invite> Invites { get; set; } = new List<Invite>();
}