// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMEFLOWSystem.Core.Entities;

/// <summary>
/// Quản lý phân quyền người dùng.
/// </summary>
public partial class Role
{
    /// <summary>Mã vai trò.</summary>
    public int Id { get; set; }

    /// <summary>Tên vai trò (VD: Admin, Manager, Employee).</summary>
    public string Name { get; set; }

    /// <summary>Mô tả vai trò.</summary>
    public string Description { get; set; }

    /// <summary>Đánh dấu vai trò mặc định của hệ thống (không thể xóa).</summary>
    public bool? IsSystemRole { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
    public virtual ICollection<Invite> Invites { get; set; } = new List<Invite>();
}