// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMEFLOWSystem.Core.Entities;

/// <summary>
/// Đại diện cho một khách hàng/doanh nghiệp thuê phần mềm.
/// </summary>
public partial class Tenant
{
    /// <summary>Mã định danh tenant.</summary>
    public Guid Id { get; set; }

    /// <summary>Tên doanh nghiệp.</summary>
    public string Name { get; set; }

    /// <summary>Trạng thái hoạt động (Active, Inactive, v.v.).</summary>
    public string Status { get; set; }

    /// <summary>Ngày hết hạn gói thuê bao.</summary>
    public DateOnly? SubscriptionEndDate { get; set; }
    /// <summary>Liên kết với User là chủ sở hữu (Admin) của Tenant này.</summary>
    public Guid? OwnerUserId { get; set; }
    /// <summary>Liên kết với User là chủ sở hữu (Admin) của Tenant này.</summary>
    public User? OwnerUser { get; set; }
    /// <summary>Tracking thông tin vòng đời của dữ liệu.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>Tracking thông tin vòng đời của dữ liệu.</summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>Tracking thông tin vòng đời của dữ liệu.</summary>
    public bool IsDeleted { get; set; }

    // ĐÃ XÓA: public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Payroll> Payrolls { get; set; } = new List<Payroll>();

    public virtual ICollection<Position> Positions { get; set; } = new List<Position>();

    public virtual ICollection<ModuleSubscription> ModuleSubscriptions { get; set; } = new List<ModuleSubscription>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
    public virtual ICollection<Invite> Invites { get; set; } = new List<Invite>();

    public virtual TenantAttendanceSetting AttendanceSetting { get; set; }
}