// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SMEFLOWSystem.SharedKernel.Interfaces;

namespace SMEFLOWSystem.Core.Entities;

/// <summary>
/// Bảng trung gian gán Role cho User.
/// </summary>
public partial class UserRole : ITenantEntity
{
    /// <summary>ID của User được gán quyền.</summary>
    public Guid UserId { get; set; }

    /// <summary>Mã định danh Tenant.</summary>
    public Guid TenantId { get; set; }

    /// <summary>ID của Role được gán.</summary>
    public int RoleId { get; set; }

    public virtual Role Role { get; set; }

    public virtual User User { get; set; }
}