// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using SMEFLOWSystem.Core.Entities;
using SMEFLOWSystem.SharedKernel.Interfaces;

namespace SMEFLOWSystem.Infrastructure.Data;

public partial class SMEFLOWSystemContext : DbContext
{
    private readonly ICurrentTenantService _currentTenantService;
    public SMEFLOWSystemContext(DbContextOptions<SMEFLOWSystemContext> options, ICurrentTenantService currentTenantService)
        : base(options)
    {
        _currentTenantService = currentTenantService;
    }

    // ĐÃ BỊ TỬ HÌNH: public virtual DbSet<Attendance> Attendances { get; set; }
    public virtual DbSet<Customer> Customers { get; set; }
    public virtual DbSet<Department> Departments { get; set; }
    public virtual DbSet<Employee> Employees { get; set; }
    public virtual DbSet<Invite> Invites { get; set; }  
    public virtual DbSet<BillingOrder> BillingOrders { get; set; }
    public virtual DbSet<BillingOrderModule> BillingOrderModules { get; set; }
    public virtual DbSet<Module> Modules { get; set; }
    public virtual DbSet<ModuleSubscription> ModuleSubscriptions { get; set; }
    public virtual DbSet<OutboxMessage> OutboxMessages { get; set; }
    public virtual DbSet<Order> Orders { get; set; }
    public virtual DbSet<OrderItem> OrderItems { get; set; }
    public virtual DbSet<PaymentTransaction> PaymentTransactions { get; set; }
    public virtual DbSet<ProcessedEvent> ProcessedEvents { get; set; }
    public virtual DbSet<Payroll> Payrolls { get; set; }
    public virtual DbSet<Position> Positions { get; set; }
    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }
    public virtual DbSet<Role> Roles { get; set; }
    public virtual DbSet<Tenant> Tenants { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<UserRole> UserRoles { get; set; }
    public virtual DbSet<TenantAttendanceSetting> TenantAttendanceSettings { get; set; }
    public virtual DbSet<Notification> Notifications { get; set; }
    
    // Các bảng mới bổ sung cho Phase 1
    public virtual DbSet<Shift> Shifts { get; set; }
    public virtual DbSet<ShiftSegment> ShiftSegments { get; set; }
    public virtual DbSet<ShiftPattern> ShiftPatterns { get; set; }
    public virtual DbSet<ShiftPatternDay> ShiftPatternDays { get; set; }
    public virtual DbSet<EmployeeShiftPattern> EmployeeShiftPatterns { get; set; }
    public virtual DbSet<OvertimeRequest> OvertimeRequests { get; set; }
    public virtual DbSet<DailyTimesheet> DailyTimesheets { get; set; }
    public virtual DbSet<DailyTimesheetSegment> DailyTimesheetSegments { get; set; }
    public virtual DbSet<DailyTimesheetAuditLog> DailyTimesheetAuditLogs { get; set; }
    public virtual DbSet<TimesheetPeriod> TimesheetPeriods { get; set; }
    public virtual DbSet<LeaveRequest> LeaveRequests { get; set; }
    public virtual DbSet<LeaveRequestSegment> LeaveRequestSegments { get; set; }
    public virtual DbSet<LeaveType> LeaveTypes { get; set; }
    public virtual DbSet<EmployeeLeaveBalance> EmployeeLeaveBalances { get; set; }
    
    // Tầng 1 (Kế Hoạch Mới): Thu thập tín hiệu
    public virtual DbSet<RawPunchLog> RawPunchLogs { get; set; }

    // HR Authorization: Manager-Department assignment (N:N)
    public virtual DbSet<ManagerDepartment> ManagerDepartments { get; set; }

    public virtual DbSet<PublicHoliday> PublicHolidays { get; set; }
    public virtual DbSet<TimesheetAppeal> TimesheetAppeals { get; set; }
    public virtual DbSet<ManualMonthlyTimesheet> ManualMonthlyTimesheets { get; set; }
    public virtual DbSet<EmployeeSalaryHistory> EmployeeSalaryHistories { get; set; }
    public virtual DbSet<EmployeeBonusDeductionEntry> EmployeeBonusDeductionEntries { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // ĐÃ XÓA: modelBuilder.Entity<Attendance>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<Customer>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<Department>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<Employee>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<RefreshToken>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<Invite>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<BillingOrder>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<BillingOrderModule>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<ModuleSubscription>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<Order>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<OrderItem>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<PaymentTransaction>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<Payroll>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<Position>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<User>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<UserRole>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<TenantAttendanceSetting>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<Notification>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);

        // Cập nhật Query Filter cho nhóm Shift & Timesheet mới
        modelBuilder.Entity<Shift>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<ShiftSegment>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<ShiftPattern>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<ShiftPatternDay>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<EmployeeShiftPattern>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<OvertimeRequest>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<DailyTimesheet>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<DailyTimesheetSegment>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<DailyTimesheetAuditLog>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<TimesheetPeriod>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<LeaveRequest>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<LeaveRequestSegment>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<LeaveType>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<EmployeeLeaveBalance>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        
        // Quá trình chia Tenant an toàn cho Raw logs
        modelBuilder.Entity<RawPunchLog>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);

        // HR Authorization: Manager-Department N:N
        modelBuilder.Entity<ManagerDepartment>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);

        modelBuilder.Entity<PublicHoliday>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<TimesheetAppeal>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<ManualMonthlyTimesheet>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<EmployeeSalaryHistory>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);
        modelBuilder.Entity<EmployeeBonusDeductionEntry>().HasQueryFilter(e => e.TenantId == _currentTenantService.TenantId);


        ApplySoftDeleteQueryFilters(modelBuilder);
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(SMEFLOWSystemContext).Assembly);
        base.OnModelCreating(modelBuilder);
    }

    private static void ApplySoftDeleteQueryFilters(ModelBuilder modelBuilder)
    {
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            var isDeletedProp = entityType.FindProperty("IsDeleted");
            if (isDeletedProp == null) continue;

            var parameter = Expression.Parameter(entityType.ClrType, "e");

            Expression isNotDeleted;
            if (isDeletedProp.ClrType == typeof(bool))
            {
                var efProperty = Expression.Call(
                    typeof(EF), nameof(EF.Property), new[] { typeof(bool) }, parameter, Expression.Constant("IsDeleted"));
                isNotDeleted = Expression.Equal(efProperty, Expression.Constant(false));
            }
            else
            {
                var efProperty = Expression.Call(
                    typeof(EF), nameof(EF.Property), new[] { typeof(bool?) }, parameter, Expression.Constant("IsDeleted"));
                isNotDeleted = Expression.NotEqual(efProperty, Expression.Constant(true, typeof(bool?)));
            }

            var existingFilter = entityType.GetQueryFilter();
            if (existingFilter == null)
            {
                entityType.SetQueryFilter(Expression.Lambda(isNotDeleted, parameter));
                continue;
            }

            var existingBody = new ReplaceExpressionVisitor(existingFilter.Parameters.Single(), parameter).Visit(existingFilter.Body);
            var combinedBody = Expression.AndAlso(existingBody!, isNotDeleted);
            entityType.SetQueryFilter(Expression.Lambda(combinedBody, parameter));
        }
    }

    private sealed class ReplaceExpressionVisitor : ExpressionVisitor
    {
        private readonly Expression _oldValue;
        private readonly Expression _newValue;

        public ReplaceExpressionVisitor(Expression oldValue, Expression newValue)
        {
            _oldValue = oldValue;
            _newValue = newValue;
        }

        public override Expression? Visit(Expression? node)
        {
            if (node == _oldValue) return _newValue;
            return base.Visit(node);
        }
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        var currentTenantId = _currentTenantService.TenantId;
        if (currentTenantId.HasValue)
        {
            foreach (var entry in ChangeTracker.Entries<ITenantEntity>())
            {
                if (entry.State == EntityState.Added)
                {
                    if (entry.Entity.TenantId == Guid.Empty)
                    {
                        entry.Entity.TenantId = currentTenantId.Value;
                    }
                }
            }
        }
        return base.SaveChangesAsync(cancellationToken);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}